Check 1: check_invariant.assertion.1\
         - Status: SUCCESS\
         - Description: "Panic: assertion failed: point.is_safe()"

Check 2: check_invariant.assertion.2\
         - Status: UNREACHABLE\
         - Description: "Panic: "this assertion should be unreachable""
