SUCCESS\
assertion failed: foo() == 42